# Generated by Django 3.0.5 on 2020-05-23 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200516_1011'),
    ]

    operations = [
    ]
